stages:
  collect-data:
    cmd: matlab -batch "run('scripts/collect_data.m');"
    deps:
      - scripts/collect_data.m
    outs:
      - data/raw/data.parquet
    meta:
      calkit:
        type: dataset
        title: Raw data
        description: The raw data from the experiment.
  plot-data:
    cmd: matlab -noFigureWindows -batch "run('scripts/plot_data.m');"
    deps:
      - scripts/plot_data.m
      - data/raw/data.parquet
    outs:
      - figures/plot.png
    meta:
      calkit:
        type: figure
        title: The plot
        description: The plot.
  plot-data-py:
    cmd: calkit runenv -n py python scripts/plot-data.py
    deps:
      - scripts/plot-data.py
      - data/raw/data.parquet
    outs:
      - figures/plot-py.png
    meta:
      calkit:
        type: figure
        title: The Pyton plot
        description: The plot created with Matplotlib.